Lock Myst-parser to a earlier version & Drop out of date Python versions
0.19 introduces a breaking change
After that we get the error:
AttributeError: 'SphinxRenderer' object has no attribute 'sphinx_env'